version: "2"

services:
  ss_ap:
    #for amd64:
    #image: yangxuan8282/ss_ap:amd64
    image: yangxuan8282/ss_ap
    restart: unless-stopped
    privileged: true
    network_mode: "host"
    environment:
      - AP_WIFI_IFACE=wlan0
      - AP_INTERNET_IFACE=eth0
      - AP_SSID=MyAccessPoint
      - AP_PASSPHRASE=MyPassPhrase 
      - SS_SERVER_IP=
      - SS_SERVER_PORT=7443
      - SS_METHOD=chacha20
      - SS_PASSWD=
      - SS_LOCAL_PORT=1080 
